### ISSUE TITLE
Feature Request: Add an option for default class assignment to icons

### ISSUE THREAD

**Issue by daralbrecht** [narciero/heroicons-rails#1]
Hi,

I'm using your `heroicons-ruby` gem in my Rails project, and I've found it incredibly helpful for integrating Heroicons. I'd like to suggest a feature that could enhance its usability: the ability to assign a default class to all icons through the gem's configuration.

The same classes are often applied to numerous icons, leading to repetitive code. Setting a default class at the configuration level would be a significant improvement. Icons could inherit these classes, reducing the need to specify them individually each time. For example:

```ruby
Heroicons.configure do |config|
  config.default_class = "h-6 w-6 text-gray-500"
end
```

Unless specifically overridden, this would automatically apply the "h-6 w-6 text-gray-500" classes to all icons.

This feature would streamline using your gem in projects where design consistency is essential. It would not only save time but also enhance code cleanliness.

Thanks for your work on this gem :)

**Comment by narciero** [comment]
@daralbrecht Good idea, implemented in #2.
